### ISSUE TITLE
Chapter 9 Slides Issue

### ISSUE THREAD

**Issue by tsteach** [robjhyndman/ETC3550Slides#14]
Hello,

When I try to knit the RMD file to generate the slides (unmodified) for 9-arima.Rmd, I receive an error on line 689.

 ```{r egyptexportsmodel, include=FALSE, warning=FALSE, dependson="egyptexportsauto"}
stopifnot(identical(
  unlist(fit[1,2][[1]][[1]]$fit$spec),
  c(p=2L, d=0L, q=1L, P=0, D=0, Q=0, constant=TRUE, period.year=1)
))
coef <- rlang::set_names(tidy(fit)$estimate, tidy(fit)$term)
```

The error is 
Error: identical(unlist(fit[1, 2][[1]][[1]]$fit$spec), c(p = 2L, d = 0L, .... is not TRUE

How do I resolve this issue?

**Comment by robjhyndman** [comment]
That may happen if you use a different version of the fable package than the one in the renv. We are using fable v0.3.2, the latest on CRAN.

**Comment by tsteach** [comment]
Thanks for the response. I just install the package "fpp3" and use it. Do I need to install the fable package separately?

**Comment by robjhyndman** [comment]
The fable package is installed with the fpp3 package. Try updating your packages to the latest versions.

**Comment by tsteach** [comment]
I updated the fpp3 package. Still the same issue while knitting. The fable package seems to be on the same version as recommended above. Anything else I need to check. Please help.

── Attaching packages ──────────────────────────────────────────────────────────────────── fpp3 0.5 ──
✔ tibble      3.1.8      ✔ tsibble     1.1.3 
✔ dplyr       1.0.10     ✔ tsibbledata 0.4.1 
✔ tidyr       1.2.1      ✔ feasts      0.3.0 
✔ lubridate   1.9.0      ✔ fable       0.3.2 
✔ ggplot2     3.4.0      ✔ fabletools  0.3.2

**Comment by robjhyndman** [comment]
It compiles for me. Try cleaning your cache.

**Comment by tsteach** [comment]
I am using the Posit Cloud. Could it be the issue? I cleared my RStudio environment by clearing the environment and all the objects. Still the same error.

**Comment by tsteach** [comment]
<img width="1027" alt="Screenshot 2023-02-12 at 4 55 03 PM" src="https://user-images.githubusercontent.com/125225003/218348443-24916151-d796-4e1b-a4b6-270453b33e8f.png">

**Comment by robjhyndman** [comment]
I think the problem is that you're using a previous release of the slides, not the latest version in this repo. Most likely you downloaded the 2022 release of the slides (which worked then but doesn't now). The latest version in the repo works fine. The difference in that code chunk is `period.year` is now `period`.

**Comment by tsteach** [comment]
That works. Thank you so much! I am closing this issue.
