### ISSUE TITLE
prediction intervals

### ISSUE THREAD

**Issue by robertgoedegebuure** [robjhyndman/ETC3550Slides#6]
thanks for the great book, and related materials.

tiny question:
in 3.5, the stdev of the residuals is given as 6.21
using **sd(residuals(naive(goog200)), na.rm=T)** I get 6.1845
where do I go wrong?

thanks

**Comment by robjhyndman** [comment]
Because the residuals have mean zero, the formula for the stdev does not involve subtracting the mean. It is simply the square root of the average of the squared residuals.

**Comment by robertgoedegebuure** [comment]
Super, thanks!
Robert

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
