### ISSUE TITLE
Request for the lectures material in editable formats 

### ISSUE THREAD

**Issue by syohn** [robjhyndman/ETC3550Slides#7]
Dear Dr. Hyndman, 

I am teaching a course on time-series data analysis in the fall semester at Korea Aerospace University, Seoul, Korea and using your book "Forecasting: Principles and Practice" as a main text book. I am very pleased to use your book and material on GitHub since they are easy to be understood and contains source codes for self-exercise for students. 

One problem I face now is that the lecturer's material is in the PDF format. I'd like to edit the material to translate text into Korean and add some supplementary explanation. But, it's very hard to edit the PDF file.
 
I wonder if you could provide the lecturer's material in the editable format like MS PPT. 

Thank you very much. 

Syng-Yup Ohn, Phd, Professor, 
Software Department, Korea Aerospace University

**Comment by robjhyndman** [comment]
The slides in this repository are in Rmd format which you can edit.
