### ISSUE TITLE
possibly some typos on the solutions of Chap 8

### ISSUE THREAD

**Issue by gcorani** [robjhyndman/ETC3550Slides#8]
In the exe of Chap 8 (arima models), it might be clearer specifying the  include.constant arguments when fitting the models.

Exe 7, point b. 
fit <- Arima(wmurders, c(0,1,2), include.constant=FALSE)

Exe 16, point b. 
When fitting the arima model, specify 
fit <- Arima(sheep, order=c(3,1,0), include.constant=FALSE)

Exe 17, point b. 
fit <- Arima(bicoal, order=c(4,0,0), include.constant=TRUE)

***

Thanks for sharing your helpful teaching material and best regards

**Comment by robjhyndman** [comment]
Thanks for the suggestions. The solutions have been updated.
